x-common-config: &common-config-template
  build:
    context: .
    dockerfile: Dockerfile
  extra_hosts:
      - "master:10.0.0.5"
      - "worker1:10.0.0.6"
      - "worker2:10.0.0.7"
      - "worker3:10.0.0.8"

services:
  master:
    <<: *common-config-template
    container_name: master
    hostname: master
    networks:
      cluster-network:
        ipv4_address: 10.0.0.5
    ports:
      - "9095:22"
    command: /bin/bash -c "./configure_mpi_hosts.sh"

  worker1:
    <<: *common-config-template
    container_name: worker1
    hostname: worker1
    networks:
      cluster-network:
        ipv4_address: 10.0.0.6
    ports:
      - "9096:22"

  worker2:
    <<: *common-config-template
    container_name: worker2
    hostname: worker2
    networks:
      cluster-network:
        ipv4_address: 10.0.0.7
    ports:
      - "9097:22"

  worker3:
    <<: *common-config-template
    container_name: worker3
    hostname: worker3
    networks:
      cluster-network:
        ipv4_address: 10.0.0.8
    ports:
      - "9098:22"

networks:
  cluster-network:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.0.0/24